"""Adversarial validation challenges.

Drives every ``fixtures/adversarial/*.json`` payload through the real validator
and asserts the expected verdict + failure code. Pass-scenarios must produce a
snapshot with the documented properties (extras preserved, nulls stay null,
sort deterministic, reproducible normalized checksum).

The fixtures are generated by ``qa/gen_adversarial_fixtures.py``; this test also
regenerates them in-process if any are missing, so it never silently skips.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from wnba_pipeline.contract import ExtractionParams, ValidationState
from wnba_pipeline.teams import resolve_expected_teams
from wnba_pipeline.validation import validate_and_normalize

from tests._builders import make_raw

REPO = Path(__file__).resolve().parents[2]
ADV = REPO / "fixtures" / "adversarial"
EXPECTED_TEAMS_FIXTURE = REPO / "fixtures" / "expected_teams" / "2026.json"

# challenge tag -> (expected verdict, a required failure code or None)
EXPECT: dict[str, tuple[str, str | None]] = {
    "changed_header_order": ("PASS", None),
    "added_column": ("PASS", None),
    "null_percentage": ("PASS", None),
    "short_season": ("PASS", None),
    "stale_upstream": ("PASS", None),
    "empty_response": ("FAIL", "EMPTY_DATASET"),
    "offseason_empty": ("FAIL", "EMPTY_DATASET"),
    "partial_response": ("FAIL", "MISSING_EXPECTED_TEAM"),
    "missing_result_set": ("FAIL", "MISSING_RESULT_SET"),
    "removed_required_column": ("FAIL", "MISSING_REQUIRED_COLUMN"),
    "row_width_mismatch": ("FAIL", "HEADER_ROW_WIDTH_MISMATCH"),
    "duplicate_team": ("FAIL", "DUPLICATE_TEAM_ID"),
    "duplicate_record": ("FAIL", "DUPLICATE_RECORD"),
    "unknown_team": ("FAIL", "UNEXPECTED_TEAM"),
    "string_instead_of_number": ("FAIL", "NON_NUMERIC_VALUE"),
    "negative_stat": ("FAIL", "NEGATIVE_COUNTING_STAT"),
    "pct_wrong_scale": ("FAIL", "PCT_SCALE_VIOLATION"),
    "wl_gp_mismatch": ("FAIL", "WL_GP_MISMATCH"),
    "makes_exceed_attempts": ("FAIL", "MAKES_EXCEED_ATTEMPTS"),
    "reb_mismatch": ("FAIL", "REB_RECONCILE_FAIL"),
    "lastn_exceeded": ("FAIL", "LASTN_EXCEEDED"),
}

# Fixtures that are not JSON envelopes (exercised by the HTTP-layer suite).
NON_ENVELOPE = {"truncated.json", "malformed.json"}


def _ensure_fixtures() -> None:
    if not ADV.exists() or not any(ADV.glob("*.json")):
        import qa.gen_adversarial_fixtures as gen  # noqa: WPS433
        gen.generate()


_ensure_fixtures()


@pytest.fixture(scope="module")
def expected_teams():
    return resolve_expected_teams("2026", fallback_path=str(EXPECTED_TEAMS_FIXTURE))


def _envelope_fixtures() -> list[Path]:
    return sorted(p for p in ADV.glob("*.json") if p.name not in NON_ENVELOPE)


def _challenge_of(path: Path) -> str:
    doc = json.loads(path.read_text(encoding="utf-8"))
    return doc.get("_provenance", {}).get("challenge", path.stem)


def test_all_challenges_have_expectations():
    """No adversarial envelope fixture is left unasserted."""
    for path in _envelope_fixtures():
        assert _challenge_of(path) in EXPECT, f"no expectation for {path.name}"


@pytest.mark.parametrize("path", _envelope_fixtures(), ids=lambda p: p.name)
def test_challenge_verdict(path, expected_teams):
    doc = json.loads(path.read_text(encoding="utf-8"))
    challenge = doc.get("_provenance", {}).get("challenge", path.stem)
    want_verdict, want_code = EXPECT[challenge]
    raw = make_raw(doc, params=ExtractionParams())
    outcome = validate_and_normalize(raw, expected_teams)
    codes = {f.code for f in outcome.failures}

    if want_verdict == "PASS":
        assert outcome.state is ValidationState.PASSED, (
            f"{challenge} expected PASS, got {outcome.state} {sorted(codes)}")
        assert outcome.snapshot is not None
    else:
        assert outcome.state is ValidationState.FAILED, (
            f"{challenge} expected FAIL, got PASS")
        assert outcome.snapshot is None
        assert want_code in codes, (
            f"{challenge} expected code {want_code}, got {sorted(codes)}")


def test_added_column_preserved_in_extras(expected_teams):
    doc = json.loads((ADV / "added_column.json").read_text())
    outcome = validate_and_normalize(make_raw(doc, params=ExtractionParams()),
                                     expected_teams)
    assert outcome.snapshot is not None
    assert all("EXTRA_OFFICIAL_STAT" in r.extras for r in outcome.snapshot.records)


def test_null_percentage_stays_null_not_zero(expected_teams):
    doc = json.loads((ADV / "null_percentage.json").read_text())
    outcome = validate_and_normalize(make_raw(doc, params=ExtractionParams()),
                                     expected_teams)
    assert outcome.snapshot is not None
    nulls = [r for r in outcome.snapshot.records if r.stats["field_goal_pct"] is None]
    assert nulls, "expected at least one record with null field_goal_pct"
    for r in nulls:
        assert r.stats["field_goal_pct"] is not 0  # noqa: F632 - explicit intent
        assert r.stats["field_goal_pct"] is None


def test_changed_header_order_matches_base_checksum(expected_teams):
    """Reordering headers must not change the normalized output at all."""
    base = json.loads(
        (REPO / "fixtures" / "sanitized"
         / "leaguedashteamstats_2026_lastn7.json").read_text())
    reordered = json.loads((ADV / "changed_header_order.json").read_text())
    o_base = validate_and_normalize(make_raw(base, params=ExtractionParams()),
                                    expected_teams)
    o_reord = validate_and_normalize(make_raw(reordered, params=ExtractionParams()),
                                     expected_teams)
    assert o_base.snapshot and o_reord.snapshot
    assert (o_base.snapshot.normalized_checksum()
            == o_reord.snapshot.normalized_checksum())


def test_sort_is_deterministic_and_reproducible(expected_teams):
    base = json.loads(
        (REPO / "fixtures" / "sanitized"
         / "leaguedashteamstats_2026_lastn7.json").read_text())
    raw = make_raw(base, params=ExtractionParams())
    s1 = validate_and_normalize(raw, expected_teams).snapshot
    s2 = validate_and_normalize(raw, expected_teams).snapshot
    names = [r.team_name for r in s1.records]
    assert names == sorted(names, key=str.lower)         # ascending by name
    assert s1.normalized_checksum() == s2.normalized_checksum()  # reproducible
